# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AuthingAws < Formula
  desc "Fetching your AWS Access token via Authing"
  homepage "https://github.com/dreampuf/authing-aws"
  version "0.0.1"
  license "GPL-3.0 license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "b0d3a0e56912ddfc52d01e7699ddf1f64cdcad8b5ef12793d39f9ef27dc9adad"

      def install
        bin.install "authing-aws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Darwin_arm64.tar.gz"
      sha256 "648580a2bfa2212c60b83604791d7bb01e4d26b9c6cc8753731a01fee209b91a"

      def install
        bin.install "authing-aws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Linux_x86_64.tar.gz"
      sha256 "c242dfcf2a4d411deb63d712ed176e9f7a3a6072529b5d7c188754fcdf01cdf8"

      def install
        bin.install "authing-aws"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dreampuf/authing-aws/releases/download/v0.0.1/authing-aws_0.0.1_Linux_arm64.tar.gz"
      sha256 "2c38ab966239118353260ae409dcacc889f369022794970961aeb99ed29babf5"

      def install
        bin.install "authing-aws"
      end
    end
  end

  test do
    system "#{bin}/program", "version"
  end
end
